### ISSUE TITLE
How can I exclude page caching? 

### ISSUE THREAD

**Issue by whaleinvasion** [pressjitsu/pj-page-cache-red#11]
Example: http://domain.com/done
need exclude **/done** link

**Comment by soulseekah** [comment]
Dmitry,

You can look around https://github.com/pressjitsu/pj-page-cache-red/blob/master/advanced-cache.php#L323 the `maybe_bail` method, it contains all decision logic for whether a request is going to be cached or not.

Use the `bail_callback` to hook your own function into this that can can read the request path and return `true` to bail. Something like:

```
$redis_page_cache_config['bail_callback'] = function() {
    if ( $_SERVER['REQUEST_URI'] == '/done' )
        return true; // Bail
}
```

(this goes into your cache configuration file)

You can use regular expressions, and other processing functions to decide whether the page should be cached or not.

Hope this makes sense and let me know what your end solution is. Suggestions, ideas and concerns welcome :)

**Comment by whaleinvasion** [comment]
Thank you very much. Exactly what is needed. I'll test

**Comment by whaleinvasion** [comment]
Thanks.
It's great to work
