### ISSUE TITLE
Incompatibility with WP_Hook class 

### ISSUE THREAD

**Issue by tzkmx** [pressjitsu/pj-page-cache-red#12]
This plugin has worked great for me before WP 4.7, since the core introduces a new handling of actions/filters based in the WP_Hook class, fortunately I'm now using NginX micro-cache.

https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/

Specifically direct access to the `$wp_filter` global now produces a fatal error since for every tag there is now a single WP_Hook object instead of the nested array of previous versions.

**Comment by soulseekah** [comment]
Fixed in b7b8103cb9736857e25af82bf66331e1678d9be4. Let us know how it goes.

**Comment by tzkmx** [comment]
Thanks for the patch!

FWIW, seems I've add my issue too early. `WP_Hook::build_preinitialized_hooks` is called just after including `advanced-cache.php` in order to convert early registered hooks with the previous hack, to WP_Hook objects, however calling the functions in the advanced-cache apparently helps to avoid another loop to rebuild the $wp_filter global.
