### ISSUE TITLE
No longer caching in Wordpress 4.9+

### ISSUE THREAD

**Issue by apple4ever** [pressjitsu/pj-page-cache-red#18]
I upgraded my server from PHP 5.6 to PHP 7.2, and its no longer caching via Redis. I checked, and it is requesting the page from Redis, but its no longer sending the cached page to Redis.

Any ideas?

**Comment by apple4ever** [comment]
Update- this actually related to Wordpress 4.9+. Sorry I swore I tested 4.9 on a PHP 5.6 and a PHP 7.2 install and the former worked, but that is wrong. Neither work.

**Comment by soulseekah** [comment]
We've been running the code on 4.9.1 systems for quite a while now, no issues at all. Can you please turn debugging on of the cache and send us the relevant headers when requesting a page twice? Thanks.

**Comment by apple4ever** [comment]
Alright so I fired up a Vagrant build that is 4.9.1 and 5.6, and that works. I'm not sure yet if there is a configuration difference (possible but shouldn't be), but the other difference is Redis runs locally there, where as in production its a separate server. 

I'm not sure how to turn on debugging of the cache or where to get the results. Can you tell me how?

Here is headers for production:

```$ curl -sv https://www.volitans-software.com/ -o /dev/null
*   Trying 45.55.84.99...
* TCP_NODELAY set
* Connected to www.volitans-software.com (45.55.84.99) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: www.volitans-software.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET / HTTP/1.1
> Host: www.volitans-software.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 09 Jan 2018 17:10:37 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Pj-Cache-Status: miss
< Set-Cookie: PsQSneAZJR=9ONh3PLZH%40; expires=Tue, 09-Jan-2018 18:10:37 GMT; Max-Age=3600; path=/
< Set-Cookie: ENiSoJcfnI=%40uBdz2ZeXa; expires=Tue, 09-Jan-2018 18:10:37 GMT; Max-Age=3600; path=/
< Set-Cookie: oqziDXfOPNSIhM=G8A4.X7MLZhi9p; expires=Tue, 09-Jan-2018 18:10:37 GMT; Max-Age=3600; path=/
< Link: <https://www.volitans-software.com/wp-json/>; rel="https://api.w.org/"
< Strict-Transport-Security: max-age=15778800
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Origin: https://www.volitans-software.com
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: no-referrer-when-downgrade
< Content-Security-Policy-Report-Only: default-src https: 'unsafe-inline' 'unsafe-eval'
< X-Content-Type-Options: nosniff
< 
{ [15459 bytes data]
* Connection #0 to host www.volitans-software.com left intact
$ curl -sv https://www.volitans-software.com/ -o /dev/null
*   Trying 45.55.84.99...
* TCP_NODELAY set
* Connected to www.volitans-software.com (45.55.84.99) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: www.volitans-software.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET / HTTP/1.1
> Host: www.volitans-software.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 09 Jan 2018 17:10:39 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Pj-Cache-Status: miss
< Set-Cookie: PsQSneAZJR=9ONh3PLZH%40; expires=Tue, 09-Jan-2018 18:10:39 GMT; Max-Age=3600; path=/
< Set-Cookie: ENiSoJcfnI=%40uBdz2ZeXa; expires=Tue, 09-Jan-2018 18:10:39 GMT; Max-Age=3600; path=/
< Set-Cookie: oqziDXfOPNSIhM=G8A4.X7MLZhi9p; expires=Tue, 09-Jan-2018 18:10:39 GMT; Max-Age=3600; path=/
< Link: <https://www.volitans-software.com/wp-json/>; rel="https://api.w.org/"
< Strict-Transport-Security: max-age=15778800
< X-Frame-Options: SAMEORIGIN
< Access-Control-Allow-Origin: https://www.volitans-software.com
< X-XSS-Protection: 1; mode=block
< Referrer-Policy: no-referrer-when-downgrade
< Content-Security-Policy-Report-Only: default-src https: 'unsafe-inline' 'unsafe-eval'
< X-Content-Type-Options: nosniff
< 
{ [15459 bytes data]
* Connection #0 to host www.volitans-software.com left intact
```

**Comment by soulseekah** [comment]
When a response contains a Set-Cookie header, the page is never cached, otherwise session poisoning would occur. Thus, both requests end up under different cache buckets as unique pages. The X-Pj-Cache-Status header shows a miss just like it's supposed to. Try with a page that does not depend on unique sessions/cookies.

You can verify this by looking at your Redis store, you'll see pages being saved there under unique keys for each unique request.

**Comment by apple4ever** [comment]
Ah okay. Looks like its due to WP-Cerber. Would be nice to be able to cache regardless of Set-Cookie.

**Comment by soulseekah** [comment]
That would result in cache poisoning, which can lead to serious vulnerabilities like issuing a logged in cookie to a non-logged in user, resulting in someone becoming logged in just like that, or XSS vulnerabilities, header injection, etc.

**Comment by apple4ever** [comment]
Well obviously you don't cache the cookie or the dynamic content. There are ways to put placeholders in the cache to fill in when supplying the page. 

Anyway, that's a separate issue. Thanks for your help.

**Comment by soulseekah** [comment]
That's fragment caching, a completely different caching strategy to full-page caching. You can check out an example of a fragment caching framework here: https://github.com/pressjitsu/fragment-cache along with our article on various fragment caching solutions for WordPress out there https://pressjitsu.com/blog/transient-cache-alternatives/

You're welcome and good luck.
