### ISSUE TITLE
Fragment Cache/Hole Punching/using it for Woocommerce

### ISSUE THREAD

**Issue by kkmuffme** [pressjitsu/pj-page-cache-red#2]
Hey,

have you thought about adding a Fragment Cache/Hole Punch capability?
I'm think of building a fragment cache solution so it can be used with (more) dyamic webshops based on woocommerce too (whereby we take the Fragment Cache capiability/Fragment marker from W3TC).

Do you have any plans for this? (so there might not be duplicate work)

**Comment by pj-dave** [comment]
Hi @DuckDagobert, unfortunately we don't have plans for implementing that in the page caching plugin, but we do have a fragment caching class available to our customers which we plan to open source soon.
