### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by valendesigns** [pressjitsu/pj-page-cache-red#21]
I'm not sure where the `pj_sapi_headers_clean()` function is suppose to be coming from, it definitely doesn't exist in the plugin. However, it's being referenced in two places [pj-page-cache.php#L146](https://github.com/pressjitsu/pj-page-cache/blob/master/pj-page-cache.php#L146) & [pj-page-cache.php#L162](https://github.com/pressjitsu/pj-page-cache/blob/master/pj-page-cache.php#L162). Could you explain what the function does and how to get it?

**Comment by soulseekah** [comment]
The function is not available outside of the Pressjitsu hosting environment. This is a proprietary function written in the C language as a PHP SAPI module. We have our own custom-compiled and patched PHP builds which are not public at the moment. It does what is says, removes all the sent headers, this is used to regenerate the an expired cache in the same request without spawning a new process. If the function is not available the cache is regenerated ad hoc in a subsequent regular client request.
