### ISSUE TITLE
video not be cached and not play

### ISSUE THREAD

**Issue by alexlii1971** [pressjitsu/pj-page-cache-red#22]
Hello

On our multisite, I am tracing the issue of video not playing in Safari After wildcard SSL setup.

Here is a video for your test, 

https://lovcour.com/testvideo/testvideo.hyperesources/mp4_video.mp4
which I uploaded by ftp, that means the issue is not related to wordpress.

Here is the screenshot in Safari Console, and it show video is not cached:

http://prntscr.com/jgtcf0

and here is cache setting in redis-hhvm.conf

cat /etc/nginx/common/redis-hhvm.conf
# Redis NGINX CONFIGURATION
# DO NOT MODIFY, ALL CHANGES LOST AFTER UPDATE EasyEngine (ee)
set $skip_cache 0;
# POST requests and URL with a query string should always go to php
if ($request_method = POST) {
set $skip_cache 1;
}
if ($query_string != “”) {
set $skip_cache 1;
}
# Don’t cache URL containing the following segments
if ($request_uri ~* “(/wp-admin/|/xmlrpc.php|wp-.*.php|index.php|/feed/|sitemap(_index)?.xml|[a-z0-9_-]+-sitemap([0-9]+)?.xml)”) {
set $skip_cache 1;
}
# Don’t cache URL containing the following segments (BuddyPress)
#if ($request_uri ~* “(/forums/|/groups/|/members/|/activity|/blogs/|/messages/|/register/|/activate/|/bpactivity/|/bp-portfolio-projects/|/bpgroup/|/activities/|/bp-social-articles.*|/bpmember/)”) {
if ($request_uri ~* “(/bpmember/)”) {
set $skip_cache 1;
}

if ($request_uri ~* “(/lovcourshow/|/ishsow/)”){
set $skip_cache 1;
}

if ($request_uri ~* “(/wechat-authorize-remote.php)”) {
set $skip_cache 1;
}
if ($request_uri ~* “(/cross-domain.php)”) {
set $skip_cache 1;
}
# Don’t use the cache for logged in users or recent commenter or customer with items in cart
if ($http_cookie ~* “comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in|woocommerce_items_in_cart”) {
set $skip_cache 1;
}
# Use cached or actual file if they exists, Otherwise pass request to WordPress
location / {
try_files $uri $uri/ /index.php?$args;
}

location /redis-fetch {
internal ;
set $redis_key $args;
redis_pass redis;
}
location /redis-store {
internal ;
set_unescape_uri $key $arg_key ;
redis2_query set $key $echo_request_body;
redis2_query expire $key 36000;
redis2_pass redis;

}

location ~ \.php$ {
set $key “nginx-cache:$scheme$request_method$host$request_uri”;
try_files $uri =404;

srcache_fetch_skip $skip_cache;
srcache_store_skip $skip_cache;

srcache_response_cache_control off;

set_escape_uri $escaped_key $key;

srcache_fetch GET /redis-fetch $key;
srcache_store PUT /redis-store key=$escaped_key;

more_set_headers ‘X-SRCache-Fetch-Status $srcache_fetch_status’;
more_set_headers ‘X-SRCache-Store-Status $srcache_store_status’;

include fastcgi_params;
fastcgi_param HTTP_ACCEPT_ENCODING “”;
fastcgi_pass hhvm;
}

I would like to ask your professional instruction on know how to set the redis cache rules to make the video playing?

Thanks in advance, and have a nice day.

Alex

**Comment by soulseekah** [comment]
Our page cache does not cache static files, PHP is never (or should never be) called for static files, so pj-page-cache-red doesn't even run. We only cache pages generated by PHP, not video files.

Sounds like you have an nginx configuration issue.
