### ISSUE TITLE
redis-page-cache-config.php doesn't seem to work

### ISSUE THREAD

**Issue by NexDog** [pressjitsu/pj-page-cache-red#24]
Might have misunderstood but I placed redis-page-cache-config.php in WP root (not /wp-content) and added the_a few variables. All that happens is that the variables are displayed in text at the top of the website.

**Comment by soulseekah** [comment]
You must have forgotten to add `<?php` at the top of the file or something. Make sure you're including the file from your wp-config.php, for example.
