### ISSUE TITLE
Cache is only hit on second call

### ISSUE THREAD

**Issue by wysow** [pressjitsu/pj-page-cache-red#3]
Hello,

First of all thanks for this really cool caching plugin for Wordpress!

I'm facing a weird behavior on a website using AWS Beanstalk and Elasticache (Redis version of course) as the `hit` is only showing up on the second refresh of the same page...

Does it sounds like a bug or a misconfiguration for you?

Thanks for any tip and/or trick about that...

**Comment by pj-dave** [comment]
If by second hit you really do mean second hit, then yes, that's normal. The page is cached during the first hit, and is served from cache during the second and following hits.

However, if by second you actually mean third, then there's likely a problem with your setup, the most common one being session or other unique cookies set during the first page view, cached during the second hit, and served from cache during the third. If that's the case then we recommend getting rid of or fixing the plugin/theme that's setting that cookie. You can inspect your server response headers for more info.

**Comment by wysow** [comment]
OK but when I said "second hit" I meant "second hit for one and only one visitor" so if I take a concrete example:

```
Visitor A come to index page => miss
Visitor B come to index page => miss
Visitor A refresh index page => hit
Visitor B refresh index page => hit
```

So if a visitor do come to see only 1 page he will never get page cache... Is it clearer like this?

And I'm not sure the 2 hits are about the same hash BTW, will check that...

**Comment by pj-dave** [comment]
Yeah, there's probably something unique about visitor A and visitor B that gives them both unique cache keys. You can check that by enabling the debug flag and looking at the response headers, but as I mentioned earlier, it's most likely some unique session cookie such as `PHPSESSID` or something along those lines.

**Comment by wysow** [comment]
OK just verified and hitting the same page with 2 different browsers from the same laptop, the page is getting 2 different cache key... Sounds normal for you?

**Comment by pj-dave** [comment]
What's the URL?

**Comment by wysow** [comment]
OK will check about some cookies along the way... Maybe Cloudflare is also mixing things up... The URL is https://siecledigital.fr

**Comment by pj-dave** [comment]
You have a `PHPSESSID` cookie, just like I suspected:

```
< Set-Cookie: PHPSESSID=ea6dp9ut0q9e39469al8lvjq04; path=/
```

**Comment by nicholas-eden** [comment]
I had the same problem.  We are on Azure unfortunately, but it turned out to be a cookie being set. 

Check your headers for the first response for a visitor.  Either Beanstalk is setting a sticky session type cookie, or a plugin is activating the php session cookie.

**Comment by wysow** [comment]
Thanks guy I will look into that and come back to you if I'm stuck, thanks for your quick answers.
