### ISSUE TITLE
Using unix socket?

### ISSUE THREAD

**Issue by Forza-tng** [pressjitsu/pj-page-cache-red#31]
Hi! Is it possible to use a unix socket instead of tcp?

Apparently the PHPRedis supports it: https://github.com/phpredis/phpredis#connection

I simply did this. Not sure it is correct. Without the port set it failes with a PHP error message.
```
    private static $redis_host = '/tmp/redis.sock';
    private static $redis_port = '0';
//  private static $redis_host = '127.0.0.1';
//  private static $redis_port = 6379;

```

**Comment by soulseekah** [comment]
Yes. You'll need to prefix the string with `unix://`
