### ISSUE TITLE
Enhancement: Add remote redis support

### ISSUE THREAD

**Issue by erikdemarco** [pressjitsu/pj-page-cache-red#34]
Hi, Its really great concept. Is there any way to add feature to use remote redis instead localhost? And ability to use custom "redis database id" will be good

**Comment by soulseekah** [comment]
Hi,

Yes, you can use the `pj_user_config` function and override any parameters: https://github.com/pressjitsu/pj-page-cache-red/blob/master/advanced-cache.php#L394

https://github.com/pressjitsu/pj-page-cache-red#configuring-the-plugin
