### ISSUE TITLE
Ignore Partial Cookie Names

### ISSUE THREAD

**Issue by greensolid** [pressjitsu/pj-page-cache-red#4]
Do you have any advise how partial cookie names could be ignored?

Piwik and Iubenda use such (e.g., _pk_id.1.ee8a, and _iub_cs-819208 accordingly). In these cases, only the prefix should be selected.

**Comment by soulseekah** [comment]
As per https://github.com/pressjitsu/pj-page-cache-red/blob/master/advanced-cache.php#L257 any cookie beginning with an underscore is ignored.

**Comment by pj-dave** [comment]
Indeed, as @soulseekah mentioned, cookies beginning with `_` are considered JavaScript-only cookies and ignored from the cache key. However, if you need to ignore cookies that don't start with an underscore, you can have a simple loop:

```
foreach ( $_COOKIE as $key => $value ) {
    if ( substr( $key, 'prefix_' ) === 0 ) {
        unset( $_COOKIE[ $key ] );
    }
}
```

That will remove your prefixed keys from the cookies, which will then not be considered when building the cache key.

Hope that helps.

**Comment by greensolid** [comment]
Thanks a lot, issue resolved.
