### ISSUE TITLE
How to differentiate cache for mobile users?

### ISSUE THREAD

**Issue by wysow** [pressjitsu/pj-page-cache-red#5]
Hello,

Using your cache system for a week or 2 and really enjoy it, but one question remains, as the title of this issue stated... 

I tried to had this line to the `$request_hash` variable: `'user-agent' => ! empty( S_SERVER['HTTP_USER_AGENT'] ) ? S_SERVER['HTTP_USER_AGENT'] : ''` (I know it should generate a lot of db rows for a single page, but it's a temporary hack so...), but it did not seems to work as expected...

What do you think of this?

**Comment by pj-dave** [comment]
You should _not_ add the user agent string to the cache key, as you said, that will generate too many rows for all the different browsers, their versions, crawlers, etc. Instead, you should create a function that would return a boolean – is this UA a mobile device or not, and then use that function in your `unique` array. For example in your cache configuration file:

```
function my_is_mobile() {
   // Stuff
}
$redis_page_cache_config['unique'] = array( my_is_mobile() );
```

Note that it's important that the function returns a boolean value and not the UA string or anything else. As for the function, you can copy the [wp_is_mobile](https://codex.wordpress.org/Function_Reference/wp_is_mobilel) function from WordPress, or the one you're using in your plugin/theme to provide mobile functionality.

Hope that helps!

**Comment by wysow** [comment]
Sure it sounds a way more like the way to go ;) Thanks a lot.
